project:
  type: website

website:
  title: "Elise Pham"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Work Experience.qmd
    background: "#783d5a"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
   
    
editor: visual

